@BasicTodoList.Server_HostAddress = http://localhost:5096/api

GET {{BasicTodoList.Server_HostAddress}}/task/
Accept: application/json

###

GET {{BasicTodoList.Server_HostAddress}}/task/1
Accept: application/json

###

DELETE {{BasicTodoList.Server_HostAddress}}/task/1

###

POST {{BasicTodoList.Server_HostAddress}}/task/
Content-Type: application/json

{
  "title": "Cleaning the house",
  "isCompleted": true
}

###
